version: '3.8'

services:

  mysql:
    image: lucaspaessptech/toomate:database
    command: --lower_case_table_names=1
    container_name: toomate_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toomate
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: lucaspaessptech/toomate:backend
    container_name: toomate_backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/toomate
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      AWS_REGION: us-east-1
      TZ: America/Sao_Paulo
    networks:
      - default
      - redis-net
    restart: always

  waha:
    image: devlikeapro/waha:latest
    container_name: toomate_waha

    env_file:
      - ../frontend/.env

    environment:
      # Define qual é a sessão "default"
      WHATSAPP_DEFAULT_SESSION: default

      # Inicia automaticamente a sessão default ao subir
      WHATSAPP_START_SESSION: default

      # Opcional: em caso de restart, tenta subir tudo de novo
      WHATSAPP_RESTART_ALL_SESSIONS: "True"

      WAHA_LOG_FORMAT: JSON
      WAHA_LOG_LEVEL: info
      TZ: America/Sao_Paulo

    ports:
      - "3000:3000"

    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    restart: unless-stopped

    # Logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  rabbitmq:
    image: 'rabbitmq:4.2.4-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_prometheus &&
               docker-entrypoint.sh rabbitmq-server"

  microservico-notif:
    image: lucaspaessptech/toomate:microservice
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=myuser
      - SPRING_RABBITMQ_PASSWORD=secret
    ports:
      - "8182:8182"
    depends_on:
      - rabbitmq

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: toomate_mysqld_exporter
    command:
      - "--mysqld.username=root:root"
      - "--mysqld.address=mysql:3306"
      - "--no-collect.slave_status"
    ports:
      - "9104:9104"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: toomate_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: always

  grafana:
    image: grafana/grafana-oss:latest
    container_name: toomate_grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-athena-datasource
      AWS_SDK_LOAD_CONFIG: "true"
      AWS_PROFILE: default
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ${USERPROFILE}/.aws:/home/grafana/.aws:ro
    depends_on:
      - prometheus
    restart: always

  redis:
    image: redis:7-alpine
    container_name: toomate_redis
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis-net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540" # UI acessível em http://localhost:5540
    depends_on:
      - redis
    networks:
      - redis-net
    volumes:
      - redisinsight_data:/data

volumes:
  mysql_data:
  waha_sessions:
    driver: local
  waha_media:
    driver: local
  prometheus_data:
  grafana_data:
  redis_data:
  redisinsight_data:

networks:
  default:
    name: toomate_network
    driver: bridge
  redis-net:
    driver: bridge